actions/checkoutのバージョン指定修正
dev-hato/hato-bot pull request #3359
Opened 2023-10-17 22:50 UTC by massongit

https://github.com/dev-hato/hato-bot/issues/1084

>Warning
>Renovate failed to look up the following dependencies: `Could not determine new digest for update (github-tags package actions/checkout)`.
>
>Files affected: `.github/workflows/pr-test.yml`

アップデート先がわからないとWarningが出ているので、 `actions/checkout` のバージョン指定をコミットハッシュではなくバージョンで指定します。

2023-10-18 00:19 UTC, Goryudyuma approved these changes

2023-10-18 00:20 UTC, Goryudyuma commented
あれ、でもこれできるはずだけどなぁ。

2023-10-18 10:45 UTC, massongit commented
できそうではあるけど、出てるものは出てるからなぁ......みたいな感じある。

2023-10-19 17:29 UTC, Goryudyuma approved these changes

2023-10-19 17:29 UTC, Goryudyuma requested changes

2023-10-19 17:29 UTC, Goryudyuma commented on .github/workflows/pr-test.yml
> +      - uses: actions/checkout@v4.1.1
あ、わかった、出てるのこいつじゃない？こいつだけv4になってる。

2023-10-19 21:39 UTC, massongit commented on .github/workflows/pr-test.yml
> +      - uses: actions/checkout@v4.1.1
ここのコメント部分だけ変えればいい感じになりそうなので、そういう感じで出し直した: https://github.com/dev-hato/hato-bot/pull/3371

2023-10-19 21:39 UTC, closed without merging