WIP: おみくじライブラリを書いた
dev-hato/hato-bot pull request #860
Opened 2022-03-05 15:48 UTC by fono09

#253 の実装を始めた

2022-03-07 15:01 UTC, massongit commented on library/omikuji.py
> +        assert self.message != ''
`test_omikuji` ではなく実コードにテストコードが記述されているのに違和感を感じてしまうが、そうする流派もある？

2022-03-07 15:09 UTC, massongit commented
📝 dataclassのドキュメント
https://docs.python.org/ja/3.10/library/dataclasses.html

2022-03-07 16:03 UTC, Goryudyuma reviewed
確率の排出率は、整数にして、
```
大吉: 1
中吉: 2
小吉: 3
```
とするのが一般的かなぁ。別に1にする必要、pythonのchoiceでは必要ないし。
そうすると、合計1にする必要もなくなるしね。

2022-03-08 10:36 UTC, fono09 commented on library/omikuji.py
> +        assert self.message != ''
最初は全部アサーションだったのが惰性でここにいるので剥がしたほうが良いと自分でも思った。

2022-03-08 10:38 UTC, fono09 commented on library/omikuji.py
> +        assert round(reduce(lambda acc, cur: acc + cur.rate,
小数点精度の保証を規格を読んでやる必要があるから、
そこらを気にせずに済むの排出率自動計算に倒すか。

2022-03-08 10:41 UTC, fono09 commented on tests/library/test_omikuji.py
> +        self.assertIn(dummy_omikuji.draw().key, DummyOmikujiResults)
おみくじ結果のkeyをEnumとして明示せず、dictのkeyに丸投げしちゃうと、keyがHashableな何かなら何でも良いことになるので直感的にキモいなと思ってしまった。

2022-03-08 10:57 UTC, Goryudyuma commented on tests/library/test_omikuji.py
> +        self.assertIn(dummy_omikuji.draw().key, DummyOmikujiResults)
どうしてもkeyを返したいなら、
```
    def draw(self) -> (TOmikujiEnum, OmikujiResult):
        """
        おみくじを引く
        """
        return choices(
            population=list(self.entries.items()),
            weights=list(map(lambda entry: entry.rate, self.entries.values())),
            k=1
        )[0]
```
とかかなぁとか考えてみたけど、うーん。ここタプルで返るのもなぁ。

> keyがHashableな何かなら何でも良いことになる

これがわからん、何かコードで例示して。おそらくEnumを満たす何かならなんでもいい、になると思ったんだけど。

2022-03-08 10:59 UTC, Goryudyuma commented on library/omikuji.py
> +        assert round(reduce(lambda acc, cur: acc + cur.rate,
まあpythonだしこのくらいは精度出るでしょってのと、
0.000009~1.000001までの保証で一般的な用途だと十分でしょって感じだな。
もうちょい精度上げたければ0を増やすか、10進数で計算できるライブラリか何かを使うかだけど、そこまでしなくてもいいかな。

2022-03-08 11:02 UTC, fono09 commented on tests/library/test_omikuji.py
> +        self.assertIn(dummy_omikuji.draw().key, DummyOmikujiResults)
Enumかつautoで縛って、静的解析レベルで壊せないコードにすることを考えていた。
ちょっとコードで例示する。

2022-03-08 11:22 UTC, fono09 commented on tests/library/test_omikuji.py
> +        self.assertIn(dummy_omikuji.draw().key, DummyOmikujiResults)
https://github.com/python/typing/issues/535
今のPythonのtypingでは表現できないっぽいので普通にkeyやって面倒なgenerics捨てることにする。

2022-03-08 12:27 UTC, Goryudyuma commented on tests/library/test_omikuji.py
> +        self.assertIn(dummy_omikuji.draw().key, DummyOmikujiResults)
> Enumかつautoで縛って、静的解析レベルで壊せないコードにすることを考えていた。

これ自体はよかったんだよな。

表現できないって言ってるのがどのことを指してるのかわからんが、
https://stackoverflow.com/questions/70146417/python-dictionary-with-enum-as-key
(stackoverflowで悪いけど、)多分こういうこと(__setitem__, __getitem__をoverride)だよね、おそらく表現はできるはできる、かな。

2022-03-09 11:19 UTC, fono09 commented on tests/library/test_omikuji.py
> +        self.assertIn(dummy_omikuji.draw().key, DummyOmikujiResults)
そのサンプルは実行時で落としているので、静的解析では蹴れない。
コードとして似たように制約を表現はしているけど起きることと落ちるタイミングが違う。

静的解析で落とせるコードにする場合、 __setitem__, __getitem__ に型アノテーションを入れて落とせるかは検討してみる価値はあるかもしれない。ちょっとやってみる。

2022-03-09 13:27 UTC, nakkaa requested changes

2022-03-09 13:27 UTC, nakkaa commented on plugins/hato.py
> +        ":dove_of_peace: 鳩吉 お前が鳩になる番だ!!羽ばたけ!!!飛べ!!!!唐揚げになれ!!!!!"
Issueの要件では揚げ吉では？

2022-03-09 13:48 UTC, nakkaa submitted a review, later dismissed

2022-03-09 14:08 UTC, nakkaa commented
Slackで動くか試験した？

2022-03-09 14:17 UTC, merged

2022-03-09 19:46 UTC, Goryudyuma commented on tests/library/test_omikuji.py
> +        self.assertIn(dummy_omikuji.draw().key, DummyOmikujiResults)
あー、なるほど、たしかに。タイミングが違うね。
むずいなこれ。今が割と仕方がないけどいい案、なのかなぁ。

2022-03-09 20:18 UTC, Goryudyuma commented on plugins/hato.py
> +        ":dove_of_peace: 鳩吉 お前が鳩になる番だ!!羽ばたけ!!!飛べ!!!!唐揚げになれ!!!!!"
どんなレビューだよw

2022-03-09 20:19 UTC, Goryudyuma commented
すご、全部解決してるじゃん！
ここだけ無駄に？最高に？型安全！